{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- $hasA3mega := gt (len (.Values.vendor.google | dig "a3mega" list)) 0 -}}
{{- if or .Values.configFiles $hasA3mega -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slurm.controller.configName" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
data:
  {{- range $key, $content := .Values.configFiles }}
  {{ $key -}}: |
    {{- $content | nindent 4 }}
  {{- end }}{{- /* range $key, $content := .Values.configFiles */}}
  {{- if and $hasA3mega (not (hasKey (.Values.configFiles | default dict) "gres.conf")) }}
  gres.conf: |
    AutoDetect=nvidia
  {{- end }}
{{- end }}{{- /* if or .Values.configFiles $hasA3mega */}}
